name: cupertino_timer
description: An iOS style countdown timer. Inspired by the native timer app on iOS.
version: 0.0.7-dev
repository: https://github.com/verygoodtechnologies/cupertino_timer

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: